export var pwaManifest = {
    id: "/?source=pwa",
    name: "Data Fuel",
    short_name: "DataFuel",
    description: "Encuentra la gasolinera más rentable según precio, distancia y consumo.",
    theme_color: "#2563EB",
    background_color: "#F4F8FC",
    display: "standalone",
    orientation: "portrait",
    start_url: "/",
    scope: "/",
    lang: "es",
    dir: "ltr",
    categories: ["navigation", "travel", "utilities"],
    icons: [
        {
            src: "/pwa-64x64.png",
            sizes: "64x64",
            type: "image/png",
        },
        {
            src: "/pwa-192x192.png",
            sizes: "192x192",
            type: "image/png",
            purpose: "any",
        },
        {
            src: "/pwa-512x512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "any",
        },
        {
            src: "/maskable-icon-512x512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
        },
    ],
    screenshots: [
        {
            src: "/screenshot-wide.png",
            sizes: "1280x720",
            type: "image/png",
            form_factor: "wide",
            label: "Data Fuel — vista escritorio con mapa y comparativa de gasolineras",
        },
        {
            src: "/screenshot-narrow.png",
            sizes: "720x1280",
            type: "image/png",
            form_factor: "narrow",
            label: "Data Fuel — vista móvil con mapa y panel inferior",
        },
    ],
};
